name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Change directory to frontend
        run: cd frontend
        
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      
      - name: Deploy to Firebase Hosting
        run: |
          npx firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting
          
